### ISSUE TITLE
Placement 'exec' is slower than inline code

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlip#10]
Testing (**test_assumptions.py**) shows that the supposedly faster `exec` code is seven times *slower* than inline if/elif/else code!  This despite us compiling the `exec` code.

Since we don't want the hassle of repeating the if/elif/else code in the 13 places we now do `exec` we would probably try to do this with a function instead of inline code.  **test_assumptions.py** shows that this approach would still be four times faster.  However, we haven't solved the problem of passing the many parameters or returning perturbed (x,y) results which could slow this further.

Leave this for the moment, but we will approach this later, say 3.1?

**Comment by rzzzwilson** [comment]
Wrote two tests in test_assumptions.py to check this.  They fail at the moment:

======================================================================
FAIL: test_dispatch_faster (__main__.TestAssumptions)
Test that dispatch is faster than inline if/elif/else.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assumptions.py", line 144, in test_dispatch_faster
    self.assertTrue(dispatch_delta < elif_delta, msg)
AssertionError: INLINE: if/else is faster than 'exec dispatch[i]'?
dispatch=1.23s, elif=0.16s (elif is 7.5 times faster)

======================================================================
FAIL: test_dispatch_faster2 (__main__.TestAssumptions)
Test that dispatch is faster than function if/elif/else.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_assumptions.py", line 204, in test_dispatch_faster2
    self.assertTrue(dispatch_delta < elif_delta, msg)
AssertionError: FUNCTION: if/else is faster than 'exec dispatch[i]'?
dispatch=1.36s, elif=0.32s (elif is 4.3 times faster)

**Comment by rzzzwilson** [comment]
Changed to a class static method to do the placement code 'perturbations'.  This also allowed a simplification in the cases where we had to preserve some state around the 'exec' statement.
