### ISSUE TITLE
Select not working in pyslip_demo.py

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlip#3]
Running pyslip_demo (GMT tiles) shows that while SELECT works, it selects the wrong point (or set of points in box select).  Also get a crash doing box select.

**Comment by rzzzwilson** [comment]
The error is triggered by trying to 'box' select points in the view-relative points layer.
```
================================================================================
Uncaught exception:
Traceback (most recent call last):
  File "/Users/r-w/git/pySlip/pyslip.py", line 1586, in OnLeftUp
    p_data = self.layerPSelHandler[l.type](l, clickpt_v)
  File "/Users/r-w/git/pySlip/pyslip.py", line 1981, in GetNearestPointInLayer
    dc = wx.BufferedPaintDC(self, self.buffer)
  File "/usr/local/lib/wxPython-3.0.0.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_gdi.py", line 5290, in __init__
    _gdi_.BufferedPaintDC_swiginit(self,_gdi_.new_BufferedPaintDC(*args, **kwargs))
PyAssertionError: C++ assertion "window->MacGetCGContextRef() != NULL" failed at /BUILD/wxPython-src-3.0.0.0/src/osx/carbon/dcclient.cpp(195) in wxPaintDCImpl(): using wxPaintDC without being in a native paint event
================================================================================
```

**Comment by rzzzwilson** [comment]
The crash appears to be due to code in GetNearestPointInLayer() that was illegal but not checked by earlier versions of wx.  Now it is checked!

The DC is used to get the width & height of the widget so we can figure out placement.  The solution is for some other code (inside a paint event!) to get DC width/height and cache it in pySlip.

**Comment by rzzzwilson** [comment]
The crash was fixed along the lines of the previous comment.  We actually used `.view_width`/`.view_height` that are set in `ResizeCallback()`.

**Comment by rzzzwilson** [comment]
Crash fixed, incorrect selection raised as another issue.
