### ISSUE TITLE
Test multi-widget

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlip#38]
Create an example program displaying 4 separate pySlip widgets.  Should be OK, but you never know!

**Comment by rzzzwilson** [comment]
Make a 4 widget example, 2 views using GMT tiles, 2 using OSM tiles.  Each view will have a TextCtrl showing geo coords on the associated view.

If/when we can change tile source allow this.

**Comment by rzzzwilson** [comment]
This has been implemented (pyslip/examples/test_multi_widget.py).

Initial testing shows that there is some interaction between widgets using the same tile source.  For example, zooming in on the first OSM widget and scrolling around works fine, but then going to the second OSM widget and attempting to scroll causes a glitch.  The second view jumps to some massively unrelated position on the map.  Also see the view sometimes going full grey.

In fact, I also got this:
================================================================================
Uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyslip-3.0.2-py2.7.egg/pyslip/pyslip.py", line 2079, in OnMouseWheel
    self.ZoomOut(gposn)
  File "/usr/local/lib/python2.7/site-packages/pyslip-3.0.2-py2.7.egg/pyslip/pyslip.py", line 2744, in ZoomOut
    self.GotoPosition(gposn)
  File "/usr/local/lib/python2.7/site-packages/pyslip-3.0.2-py2.7.egg/pyslip/pyslip.py", line 1413, in GotoPosition
    (xtile, ytile) = self.tiles.Geo2Tile(geo)
  File "/usr/local/lib/python2.7/site-packages/pyslip-3.0.2-py2.7.egg/pyslip/osm_tiles.py", line 719, in Geo2Tile
    ytile = ((1.0 - math.log(math.tan(lat_rad) + (1.0/math.cos(lat_rad))) / math.pi) / 2.0) * n
ValueError: math domain error
================================================================================

**Comment by rzzzwilson** [comment]
Further testing on the "glitch" mentioned above shows that the glitch zoom change is the second widget going to the same zoom as the first.  So there's some interaction here.  Also noticed that the "glitched" widget seems to lose it's notion of where the map edge is.  It's possible to drag scroll its map almost totally off the view.  There's code to stop this, so there must be some commonality there screwing the code.

Also noticed that (after a glitch) zooming one widget will also (sometimes) zoom the other widget.  Possible "broadcast" of events to other/wrong widget.  This has only been observed in the OSM widgets, not GMT.

Suggest initially working with GMT widgets.  This way we can ignore any problems in the internet code for OSM tiles and work on the common code

**Comment by rzzzwilson** [comment]
Modified test_multi_widget.py to use GMT tiles in all four widgets.  Still have the "zoom one, other has problems" bug **but only in the pairs that were originally GMT/OSM previously**???

In the example code this means that changing the zoom in the top-left widget results in the bug manifesting in the bottom-right widget, not in either of the other two.

Also noticed that at initial start the "pairs" of widgets centre at a different position.  They are supposed to centre on Bangkok.  Temporarily shifting two widgets back to OSM **does** get those widgets centred on Bangkok.

Also got this when zooming in to a "glitched" window:

```
Uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyslip-3.0.2-py2.7.egg/pyslip/pyslip.py", line 2075, in OnMouseWheel
    if self.ZoomToLevel(self.level + 1):
  File "/usr/local/lib/python2.7/site-packages/pyslip-3.0.2-py2.7.egg/pyslip/pyslip.py", line 2258, in ZoomToLevel
    self.tiles.UseLevel(level)
  File "/usr/local/lib/python2.7/site-packages/pyslip-3.0.2-py2.7.egg/pyslip/gmt_local_tiles.py", line 156, in UseLevel
    raise Exception("Level '%s' not used" % str(level))
Exception: Level '5' not used
```

which is correct: GMT tiles only have levels 0 to 4.  There is code to prevent this, which must be confused by "reentrancy".

**Comment by rzzzwilson** [comment]
Fixed.  After *some thought* (!) it's apparent that there must be a unique Tile source for each widget.  The unique Tile objects may have the same tile directory, though.

The test code (pyslip/examples/test_multi_widget.py) now works correctly.
