### ISSUE TITLE
Crash on right-click in test_multi_widget.py

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlip#55]
When running *test_multi_widget.py* and right-clicking on either OSM tile widget, we get a crash:

    $ python3 test_multi_widget.py
    =======================================================================
    Uncaught exception:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/pyslip-4.0.0-py3.6.egg/pyslip/pyslip.py", line 2077, in OnRightUp
        click_g = self.tile_src.Tile2Geo((click_vx, click_vy))
      File "/usr/local/lib/python3.6/dist-packages/pyslip-4.0.0-py3.6.egg/pyslip/osm_tiles.py", line 118, in Tile2Geo
        yrad = math.atan(math.sinh(math.pi * (1 - 2 * ytile / n)))
    OverflowError: math range error
    =======================================================================

**Comment by rzzzwilson** [comment]
Closed.  Fixed by removing any action on middle and right mouse buttons.

Also made behaviour when switching between to pySlip widgets more sensible.
