### ISSUE TITLE
OSM tiles not behaving

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlip#61]
When running *test_osm_tiles.py* I get:

    E
    ======================================================================
    ERROR: testSimple (__main__.TestOSMTiles)
    Simple tests.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test_osm_tiles.py", line 52, in testSimple
        cache = tiles.Tiles(tiles_dir=TilesDir)
      File "/usr/local/lib/python3.6/dist-packages/pyslip-4.0.0-py3.6.egg/pyslip/open_street_map.py", line 67, in __init__
        max_lru=MaxLRU)
      File "/usr/local/lib/python3.6/dist-packages/pyslip-4.0.0-py3.6.egg/pyslip/tiles_net.py", line 217, in __init__
    raise RuntimeError(msg) from None
    RuntimeError: You got a 429 error from: https://a.tile.openstreetmap.org/0/0/0.png
    You are asking for too many tiles.
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.757s
    
    FAILED (errors=1)

This **used to** work.  Maybe OpenStreetMap has changed tile policy, or maybe my IP is blacklisted.

**Comment by fivitti** [comment]
Hi!
Thanks for your approve. 
You wrote that you cannot test my changes. Maybe I should write some unit test for this solution?

**Comment by rzzzwilson** [comment]
Hi Slawomir,

Write test cases if you want, but I can't test wxpython applications on
MacOS, because after installing wxpython into a virtual environment pySlip
crashes with a "framework" error.  This is a known problem, with a
complicated fix.  Due to this and the slowness in moving to python 3 I have
long ago moved to PyQt, which has no problem working in a virtual
environment.

Ross
