### ISSUE TITLE
Locale problem?

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlip#63]
Eddy found this problem when running pyslip_demo.py under Windows (10?):

```
== RESTART: C:\Python 3.7\Lib\site-packages\pyslip\examples\pyslip_demo.py ==
Traceback (most recent call last):
  File "C:\Python 3.7\Lib\site-packages\pyslip\examples\pyslip_demo.py", line 2268, in <module>
    app_frame = AppFrame()
  File "C:\Python 3.7\Lib\site-packages\pyslip\examples\pyslip_demo.py", line 288, in __init__
    self.make_gui(self.panel)
  File "C:\Python 3.7\Lib\site-packages\pyslip\examples\pyslip_demo.py", line 339, in make_gui
    style=wx.SIMPLE_BORDER)
  File "C:\Python 3.7\lib\site-packages\pyslip\pyslip.py", line 453, in __init__
    self.ChangeTileset(tile_src)
  File "C:\Python 3.7\lib\site-packages\pyslip\pyslip.py", line 579, in ChangeTileset
    self.GotoLevelAndPosition(level, geo)
  File "C:\Python 3.7\lib\site-packages\pyslip\pyslip.py", line 1475, in GotoLevelAndPosition
    if self.GotoLevel(level):
  File "C:\Python 3.7\lib\site-packages\pyslip\pyslip.py", line 1434, in GotoLevel
    self.OnSize()
  File "C:\Python 3.7\lib\site-packages\pyslip\pyslip.py", line 148, in OnSize
    self.Update()
  File "C:\Python 3.7\lib\site-packages\pyslip\pyslip.py", line 121, in Update
    self.Draw(dc)
  File "C:\Python 3.7\lib\site-packages\pyslip\pyslip.py", line 2173, in Draw
    tile = self.tile_src.GetTile(x, y)
  File "C:\Python 3.7\lib\site-packages\pyslip\tiles.py", line 205, in GetTile
    return self.cache[(self.level, x, y)]
  File "C:\Python 3.7\lib\site-packages\pyslip\pycacheback.py", line 28, in __getitem__
    value = self._get_from_back(key)
  File "C:\Python 3.7\lib\site-packages\pyslip\tiles.py", line 77, in _get_from_back
    return wx.Image(file_path, Cache.TileDiskFormat).ConvertToBitmap()
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
 ```

Note that this problem rises when reading a tile from disk and trying to create a bitmap object.  Nowhere in pySlip code is `setlocale()` called or any other mention of `locale` found?

**Comment by rzzzwilson** [comment]
After a bit of googling, I found a [mention of the problem](https://stackoverflow.com/questions/21444951/wxpython-3-0-breaks-older-apps-locale-error) (for wxPython 3.x).  It appears that since pySlip never sets the locale there can be problems.  Works fine on Linux!

**Comment by rzzzwilson** [comment]
I have put these lines at the very start of the GUI code in *pyslip_demo.py*:

        def __init__(self):
            super().__init__(None, size=(DemoWidth, DemoHeight),
                                   title='%s %s' % (DemoName, DemoVersion))
    
            # set locale to ENGLISH, object must persist
            self.locale = wx.Locale(wx.LANGUAGE_ENGLISH)

I have no idea if they fix the original problem since I'll have to install Windows 7 and see if the error happens for me.  I'll put the changed code up on PyPi as 4.0.5 and see what happens.

**Comment by rzzzwilson** [comment]
Eddy has tested this and it seems to fix the problem.
